FROM node:20.11.0-alpine

RUN npm install -g serve

RUN mkdir /home/node/app/

WORKDIR /home/node/app/

COPY . .

RUN npm i

RUN npm run build

EXPOSE 8080

ENV PORT 8080

CMD [ "serve", "dist", "-s" ]